#------------#
# Appearance #
#------------#

gaps inner 8
gaps outer 0
default_border pixel 2
default_floating_border pixel 2
font pango:JetBrainsMono Nerd Font 10

# ---colors---
# format: client.<class> <border> <background> <text> <indicator>

client.focused          #424242 #343434 #F7F7F7 #4A7FB5
client.focused_inactive #343434 #282828 #E5E5E5 #424242
client.unfocused        #282828 #1E1E1E #B8B8B8 #282828
client.placeholder      #181818 #181818 #B8B8B8 #181818
client.urgent           #7E97B6 #282828 #F7F7F7 #6FA0D0
client.background       #111111


# ---optionals---
# smart_gaps on
# smart_borders on
# titlebar_padding 6 4
# hide_edge_borders smart
