#-----------#
# Autostart #
#-----------#

exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # --systemd flag is harmless
exec mako
exec wl-paste --watch cliphist store
exec awww-daemon
exec /usr/lib/polkit-kde-authentication-agent-1
exec waybar
exec pipewire