#-----------#
# Variables #
#-----------#

set $mod Mod4
set $term foot
set $menu fuzzel
set $browser brave-browser-stable
set $filemanager nautilus
set $screenshot grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%s).png
set $lock swaylock -f -c 000000